# Google Cloud Build configuration for Hail-Mary
# This file defines the build steps for deploying all services to Google Cloud Run
#
# Prerequisites:
# 1. Enable required APIs:
#    - Cloud Build API
#    - Cloud Run API
#    - Artifact Registry API
#    - Secret Manager API
# 2. Create secrets in Secret Manager:
#    - DATABASE_URL
#    - JWT_SECRET
#    - GEMINI_API_KEY (optional, for assistant)
# 3. Grant Cloud Build service account permissions:
#    - Cloud Run Admin
#    - Service Account User
#    - Secret Manager Secret Accessor
#
# Manual deployment:
#   gcloud builds submit --config cloudbuild.yaml
#
# Automated deployment (GitHub trigger):
#   Set up a Cloud Build trigger connected to your GitHub repo

options:
  # Use newer machine type for faster builds
  machineType: 'E2_HIGHCPU_8'
  # Increase timeout for monorepo builds
  timeout: '1200s'

substitutions:
  _REGION: 'us-central1'
  _API_SERVICE_NAME: 'hail-mary-api'
  _ASSISTANT_SERVICE_NAME: 'hail-mary-assistant'
  _PWA_SERVICE_NAME: 'hail-mary-pwa'
  _ARTIFACT_REGISTRY: 'us-central1-docker.pkg.dev/${PROJECT_ID}/hail-mary'

steps:
  # Step 1: Build API Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api'
    args:
      - 'build'
      - '-f'
      - 'packages/api/Dockerfile'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/api:${SHORT_SHA}'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/api:latest'
      - '.'
    dir: '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # Step 2: Build Assistant Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-assistant'
    args:
      - 'build'
      - '-f'
      - 'packages/assistant/Dockerfile'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/assistant:${SHORT_SHA}'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/assistant:latest'
      - '.'
    dir: '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # Step 3: Build PWA Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-pwa'
    args:
      - 'build'
      - '-f'
      - 'packages/pwa/Dockerfile'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/pwa:${SHORT_SHA}'
      - '-t'
      - '${_ARTIFACT_REGISTRY}/pwa:latest'
      - '.'
    dir: '.'
    env:
      - 'DOCKER_BUILDKIT=1'

  # Step 4: Push API image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/api'
    waitFor: ['build-api']

  # Step 5: Push Assistant image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-assistant'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/assistant'
    waitFor: ['build-assistant']

  # Step 6: Push PWA image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-pwa'
    args:
      - 'push'
      - '--all-tags'
      - '${_ARTIFACT_REGISTRY}/pwa'
    waitFor: ['build-pwa']

  # Step 7: Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-api'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_API_SERVICE_NAME}'
      - '--image=${_ARTIFACT_REGISTRY}/api:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3001'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production,PORT=3001'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,JWT_SECRET=JWT_SECRET:latest'
      - '--timeout=300s'
    waitFor: ['push-api']

  # Step 8: Deploy Assistant to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-assistant'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_ASSISTANT_SERVICE_NAME}'
      - '--image=${_ARTIFACT_REGISTRY}/assistant:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3002'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--set-env-vars=NODE_ENV=production,ASSISTANT_PORT=3002,GEMINI_MODEL=gemini-1.5-flash'
      - '--set-secrets=DATABASE_URL=DATABASE_URL:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest'
      - '--timeout=300s'
    waitFor: ['push-assistant', 'deploy-api']

  # Step 9: Get API URL and set it as env var for Assistant
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-assistant-api-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        API_URL=$(gcloud run services describe ${_API_SERVICE_NAME} --region=${_REGION} --format='value(status.url)')
        if [ -z "$API_URL" ]; then
          echo "Error: Failed to retrieve API URL"
          exit 1
        fi
        echo "API URL: $API_URL"
        # Note: Double dollar sign ($$) is required for Cloud Build variable escaping
        # This ensures the API_URL value is passed correctly to the gcloud command
        gcloud run services update ${_ASSISTANT_SERVICE_NAME} \
          --region=${_REGION} \
          --set-env-vars=API_BASE_URL=$${API_URL}
    waitFor: ['deploy-assistant']

  # Step 10: Deploy PWA to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-pwa'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_PWA_SERVICE_NAME}'
      - '--image=${_ARTIFACT_REGISTRY}/pwa:${SHORT_SHA}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'
      - '--memory=256Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=10'
      - '--set-env-vars=NODE_ENV=production'
      - '--timeout=60s'
    waitFor: ['push-pwa']

# Store built images
images:
  - '${_ARTIFACT_REGISTRY}/api:${SHORT_SHA}'
  - '${_ARTIFACT_REGISTRY}/api:latest'
  - '${_ARTIFACT_REGISTRY}/assistant:${SHORT_SHA}'
  - '${_ARTIFACT_REGISTRY}/assistant:latest'
  - '${_ARTIFACT_REGISTRY}/pwa:${SHORT_SHA}'
  - '${_ARTIFACT_REGISTRY}/pwa:latest'
