/**
 * Rocky Logic Engine Types
 * 
 * Rocky is a deterministic, auditable logic engine that:
 * - Consumes transcripts / natural notes
 * - Derives structured facts and decisions
 * - Outputs automaticNotes, engineerBasics, and versioned RockyFacts JSON
 * - Contains NO LLM usage, NO tone, NO prose
 * 
 * Architectural Rule: Rocky decides. Sarah explains.
 */

// ============================================
// RockyFacts - Versioned JSON Contract
// ============================================

/**
 * RockyFactsV1 - The first version of Rocky's structured fact output
 * This is a versioned contract consumed by Sarah and other systems
 */
export interface RockyFactsV1 {
  version: '1.0.0';
  
  // Core metadata
  sessionId: number;
  processedAt: Date;
  naturalNotesHash: string; // Hash of source transcript for auditability
  
  // Derived facts (deterministic, no LLM interpretation)
  facts: {
    // Customer information (extracted verbatim)
    customer?: {
      firstName?: string;
      lastName?: string;
      address?: string;
      contactPreference?: string;
    };
    
    // Property details (factual measurements and observations)
    property?: {
      type?: 'house' | 'flat' | 'bungalow' | 'other';
      bedrooms?: number;
      yearBuilt?: number;
      wallConstruction?: string;
      roofType?: string;
    };
    
    // Existing system (direct observations only)
    existingSystem?: {
      boilerMake?: string;
      boilerModel?: string;
      boilerAge?: number;
      systemType?: 'combi' | 'system' | 'regular' | 'other';
      fuelType?: 'gas' | 'oil' | 'electric' | 'lpg' | 'other';
      condition?: 'working' | 'faulty' | 'condemned';
    };
    
    // Measurements (raw numbers only)
    measurements?: {
      pipeSize?: string; // e.g., "15mm", "22mm"
      radiatorCount?: number;
      cylinderCapacity?: number;
      mainFuseRating?: number;
    };
    
    // Materials mentioned (extracted from transcript)
    materials?: Array<{
      name: string;
      quantity?: number;
      unit?: string;
    }>;
    
    // Hazards (factual observations only)
    hazards?: Array<{
      type: string;
      location: string;
      severity: 'low' | 'medium' | 'high';
    }>;
    
    // Actions required (derived from facts, not interpretation)
    requiredActions?: Array<{
      action: string;
      reason: string; // Factual reason based on extracted data
      priority: 'critical' | 'important' | 'optional';
    }>;
  };
  
  // Data completeness (calculated, not interpreted)
  completeness: {
    customerInfo: number; // 0-100
    propertyDetails: number; // 0-100
    existingSystem: number; // 0-100
    measurements: number; // 0-100
    overall: number; // 0-100
  };
  
  // Missing data (gaps in facts, not interpretation)
  missingData: Array<{
    category: string;
    field: string;
    required: boolean;
  }>;
}

/**
 * RockyFacts - Union type for all versions
 * As new versions are added, extend this union
 */
export type RockyFacts = RockyFactsV1;

// ============================================
// Rocky Input/Output Types
// ============================================

/**
 * Natural Notes - Verbatim transcript input to Rocky
 * Stored exactly as transcribed, editable by users
 */
export interface NaturalNotes {
  id?: number;
  sessionId: number;
  rawTranscript: string;
  editedTranscript?: string; // User-edited version if different from raw
  language: string;
  recordedAt: Date;
  editedAt?: Date;
}

/**
 * Automatic Notes - Rocky's structured output
 * Generated by Rocky from RockyFacts, not from transcript
 */
export interface AutomaticNotes {
  id?: number;
  sessionId: number;
  rockyFactsVersion: string;
  
  // Structured sections derived from facts
  sections: {
    customerSummary: string; // Factual summary from customer facts
    propertyOverview: string; // Factual property description
    systemDetails: string; // Factual existing system details
    measurementsAndSizes: string; // Factual measurements
    materialsRequired: string; // List from materials facts
    hazardsIdentified: string; // List from hazards facts
    nextSteps: string; // Derived from requiredActions facts
  };
  
  generatedAt: Date;
}

/**
 * Engineer Basics - Fixed format summary for engineers
 * Rocky-generated, copy-only format, no interpretation
 */
export interface EngineerBasics {
  id?: number;
  sessionId: number;
  rockyFactsVersion: string;
  
  // Fixed format fields (populated from facts, empty if missing)
  basics: {
    // Property (one-line facts)
    propertyType?: string;
    bedrooms?: string;
    
    // System (one-line facts)
    boilerMakeModel?: string;
    boilerAge?: string;
    systemType?: string;
    
    // Critical measurements (one-line facts)
    pipeSize?: string;
    mainFuse?: string;
    
    // Materials (bullet list from facts)
    materials: string[];
    
    // Hazards (bullet list from facts)
    hazards: string[];
    
    // Actions (bullet list from facts)
    actions: string[];
  };
  
  generatedAt: Date;
}

// ============================================
// Rocky Processing Types
// ============================================

/**
 * Rocky processing request
 */
export interface RockyProcessRequest {
  sessionId: number;
  naturalNotes: string; // Raw or edited transcript
  language?: string;
}

/**
 * Rocky processing result
 */
export interface RockyProcessResult {
  success: boolean;
  rockyFacts: RockyFacts;
  automaticNotes: AutomaticNotes;
  engineerBasics: EngineerBasics;
  processingTimeMs: number;
  errors?: string[];
  warnings?: string[];
}

// ============================================
// Rocky Configuration
// ============================================

/**
 * Rocky configuration (deterministic rules, no LLM config)
 */
export interface RockyConfig {
  // Version of Rocky engine
  engineVersion: string;
  
  // Extraction rules
  extractionRules: {
    customerInfoPatterns: RegExp[];
    measurementPatterns: RegExp[];
    materialKeywords: string[];
    hazardKeywords: string[];
  };
  
  // Validation rules
  validationRules: {
    requiredFields: string[];
    criticalMeasurements: string[];
  };
  
  // Normalization rules
  normalizationRules: {
    pipeSizes: { pattern: RegExp; normalized: string }[];
    boilerTypes: { pattern: RegExp; normalized: string }[];
  };
}
