// Generated by Wrangler by running `wrangler types`

interface Env {
	SARAH_MODEL: "gemini-1.5-flash";
	SARAH_TEMPERATURE: "0.3";
	SARAH_MAX_TOKENS: "500";
	ROCKY_MODEL: "gemini-1.5-pro";
	ROCKY_TEMPERATURE: "0.2";
	ROCKY_MAX_TOKENS: "600";
}
